### ISSUE TITLE
Cannot read property appVersion of undefined - iOS

### ISSUE THREAD

**Issue by thebergamo** [APSL/react-native-version-number#14]
It works perfect in Android version, but in iOS version, I'm receiving this error. 

I tried to use version 0.3.0 (Currently using 0.2.0) but I got some errors trying to install via yarn, it throws an error about access in some git files.

I already try `react-native link` but nothing happens. 

Any clue?

![screen shot 2017-11-01 at 17 15 34](https://user-images.githubusercontent.com/1778730/32284723-628d3e24-bf28-11e7-95f0-44b2b61ab1bc.png)

**Comment by morksinaanab** [comment]
I had the same. Fixed now:
Did you make sure 
1. you used `--save` so it's in your package.json
2. when you run `react-native link` you see in the output it is linked
3. after you've run react native link made sure you build the app again (i.e. react-native run-ios) instead of just (hot)reloading? -> and to be sure clean the project in xcode before building again

**Comment by morksinaanab** [comment]
the problem with git is mentioned in this issue: https://github.com/APSL/react-native-version-number/issues/13
basically for now remove the .git folder from the node-module/react-native-version-number folder

**Comment by kalanaw** [comment]
I'm having the same issue (only iOS, works fine for Android) and what @morksinaanab described did not work for me.
Anyone know how to double check if iOS is linked properly? May be manual linking steps would help.

**Comment by nicoara** [comment]
why is this closed??

**Comment by samwangdd** [comment]
you should 'run-ios/android', after 'react-native link'
